const catalog = [
  {
    title: "Guitar",
    image: "/images/guitar.webp",
    price: 1049.99,
    category: "instrument",
    _id: "1",
  },
  {
    title: "Drums",
    image: "/images/drums.webp",
    price: 399.99,
    category: "instrument",
    _id: "2",
  },
  {
    title: "Trumpet",
    image: "/images/trumpet.jpg",
    price: 892.49,
    category: "instrument",
    _id: "3",
  },
  {
    title: "Guitar Strings",
    image: "/images/guitarstrings.webp",
    price: 19.99,
    category: "maintenance",
    _id: "4",
  },
  {
    title: "Drumsticks",
    image: "/images/drumsticks.webp",
    price: 44.99,
    category: "equipment",
    _id: "5",
  },
  {
    title: "Valve Oil",
    image: "/images/valveoil.jpg",
    price: 5.99,
    category: "maintenance",
    _id: "6",
  },
  {
    title: "Microphone",
    image: "/images/microphone.jpg",
    price: 99,
    category: "equipment",
    _id: "7",
  },
  {
    title: "XLR Cable",
    image: "/images/xlr.webp",
    price: 21.99,
    category: "equipment",
    _id: "8",
  },
  {
    title: "Speaker",
    image: "/images/speaker.jpg",
    price: 699,
    category: "equipment",
    _id: "9",
  },
  {
    title: "Staff Paper",
    image: "/images/staffpaper.webp",
    price: 4.99,
    category: "accessory",
    _id: "10",
  },
  {
    title: "Music Stand",
    image: "/images/musicstand.webp",
    price: 49.99,
    category: "accessory",
    _id: "11",
  },
];
